version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-local
    ports:
      - "8081:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for Docker-in-Docker
      - /usr/local/bin/docker:/usr/local/bin/docker  # Docker binary
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    restart: unless-stopped

  # Couchbase for testing
  couchbase:
    image: couchbase/server:7.0.2
    platform: linux/amd64
    container_name: jenkins-couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=123456
    volumes:
      - couchbase_data:/opt/couchbase/var
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/pools/default"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jenkins_home:
  couchbase_data:
